import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col items-center selection:bg-indigo-500 selection:text-white overflow-x-hidden`}
      >

        <div className="w-full max-w-4xl px-4 py-8 flex-1 flex flex-col relative z-10">
          {children}
        </div>

        <footer className="w-full py-6 text-center text-slate-500 text-xs border-t border-slate-800">
          <p>Smart Bookmarks • Realtime Manager</p>
        </footer>
      </body>
    </html>
  );
}
